# Generated by Django 4.1.1 on 2022-09-08 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('E_compaign', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
